version: '3'

services:
  consumer:
    build: ./src/consumer
    depends_on: 
      - rapids
    ports: 
      - 8080:8080
    volumes: 
      - ./src/consumer/node_modules:/app/node_modules
      - ./src/consumer:/app
  
  rapids:
    image: confluentinc/cp-kafka:5.3.2
    depends_on: 
      - zookeeper
    environment: 
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports: 
      - 9092:9092
  
  zookeeper:
    image: zookeeper:3.5
    ports: 
      - 2181:2181