version: '3'

services:
  # Infastructure: The foundational event stream
  core_rapids:
    image: confluentinc/cp-kafka:5.3.2
    depends_on: 
      - core_zookeeper
    environment: 
      KAFKA_ADVERTISED_LISTENERS: LISTENER_INTERNAL://core_rapids:29092,LISTENER_EXTERNAL://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_INTERNAL
      KAFKA_LISTENERS: LISTENER_INTERNAL://core_rapids:29092,LISTENER_EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_INTERNAL:PLAINTEXT,LISTENER_EXTERNAL:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: core_zookeeper:2181
    ports:
      - 9092:9092
  
  core_zookeeper:
    image: zookeeper:3.5
    ports: 
      - 2181:2181

  # Standalone: isolated service to mess around with admin, producers, and consumers concepts
  standalone:
    build: ./src/standalone
    depends_on:
      - core_rapids
    volumes:
      - ./src/standalone:/app

  # Application Hydrator: Transfer messages from rapids to river
  example-service_hydrator:
    build: ./src/example-service/hydrator
    depends_on:
      - core_rapids
    volumes:
      - ./src/example-service/hydrator:/app
