version: "3"

services:
  address:
    build: ./address
    volumes:
      - ./address/node_modules:/app/node_modules
      - ./address:/app

  address-h:
    build: ./address-h
    depends_on:
      - address
      - river
    environment:
      CONTACT_ADDRESS_URL: ${CONTACT_ADDRESS_URL}
      CONTACT_RIVER_URL: ${CONTACT_RIVER_URL}
      CORE_RAPIDS_URL: ${CORE_RAPIDS_URL}
    volumes:
      - ./address-h/node_modules:/app/node_modules
      - ./address-h:/app

  river:
    image: confluentinc/cp-kafka:5.4.1
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${CONTACT_RIVER_HOST}
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:${CONTACT_RIVER_PORT_INSIDE},OUTSIDE://:${CONTACT_RIVER_PORT_OUTSIDE}
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_LISTENERS: INSIDE://:${CONTACT_RIVER_PORT_INSIDE},OUTSIDE://:${CONTACT_RIVER_PORT_OUTSIDE}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: ${CONTACT_ZOOKEEPER_URL}
    ports:
      - ${CONTACT_RIVER_PORT_OUTSIDE}:${CONTACT_RIVER_PORT_OUTSIDE}

  river-h:
    build: ./river-h
    depends_on:
      - river
    environment:
      CONTACT_RIVER_URL: ${CONTACT_RIVER_URL}
      CORE_RAPIDS_URL: ${CORE_RAPIDS_URL}
      CORE_RESULTS_URL: ${CORE_RESULTS_URL}
    volumes:
      - ./river-h/node_modules:/app/node_modules
      - ./river-h:/app

  zookeeper:
    image: zookeeper:3.5
