version: '3.5'

services:
  address:
    build: ./address
    environment:
      PORT: ${CONTACT_ADDRESS_PORT}
    networks:
      - contact-address-internal-network
    volumes:
      - ./address/node_modules:/app/node_modules
      - ./address:/app

  address-h:
    build: ./address-h
    depends_on:
      - address
      - river
    environment:
      CONTACT_ADDRESS_URL: ${CONTACT_ADDRESS_HOST}:${CONTACT_ADDRESS_PORT}
      CONTACT_RIVER_URL: ${CONTACT_RIVER_HOST}:${CONTACT_RIVER_PORT}
      CORE_RAPIDS_URL: ${CORE_RAPIDS_HOST}:${CORE_RAPIDS_PORT}
    networks:
      - contact-address-internal-network
      - contact-river-network
      - core-rapids-network
    volumes:
      - ./address-h/node_modules:/app/node_modules
      - ./address-h:/app

  river:
    image: confluentinc/cp-kafka:5.4.1
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://:${CONTACT_RIVER_INTERNAL_PORT},EXTERNAL://:${CONTACT_RIVER_PORT}
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: INTERNAL://:${CONTACT_RIVER_INTERNAL_PORT},EXTERNAL://:${CONTACT_RIVER_PORT}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: ${CONTACT_ZOOKEEPER_HOST}:${CONTACT_ZOOKEEPER_PORT}
    networks:
      - contact-river-internal-network
      - contact-river-network
    ports:
      - ${CONTACT_RIVER_PORT}:${CONTACT_RIVER_PORT}

  river-h:
    build: ./river-h
    depends_on:
      - river
    environment:
      CONTACT_RIVER_URL: ${CONTACT_RIVER_HOST}:${CONTACT_RIVER_PORT}
      CORE_RAPIDS_URL: ${CORE_RAPIDS_HOST}:${CORE_RAPIDS_PORT}
    networks:
      - contact-river-network
      - core-rapids-network
    volumes:
      - ./river-h/node_modules:/app/node_modules
      - ./river-h:/app

  zookeeper:
    image: zookeeper:3.5
    networks:
      - contact-river-internal-network

networks:
  contact-address-internal-network: {}
  contact-river-internal-network: {}
  contact-river-network: {}
  core-rapids-network:
    name: core-rapids-network
