version: "3"

services:
  rapids:
    image: confluentinc/cp-kafka:5.4.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_INTERNAL://${CORE_RAPIDS_HOST}:29092,LISTENER_EXTERNAL://${CORE_RAPIDS_HOST}:${CORE_RAPIDS_PORT}
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_INTERNAL
      KAFKA_LISTENERS: LISTENER_INTERNAL://${CORE_RAPIDS_HOST}:29092,LISTENER_EXTERNAL://${CORE_RAPIDS_HOST}:${CORE_RAPIDS_PORT}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_INTERNAL:PLAINTEXT,LISTENER_EXTERNAL:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: ${CORE_ZOOKEEPER_URL}
    ports:
      - ${CORE_RAPIDS_PORT}:${CORE_RAPIDS_PORT}

  zookeeper:
    image: zookeeper:3.5
