version: "3"

services:
  rapids:
    image: confluentinc/cp-kafka:5.4.1
    depends_on:
      - rapids-zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${CORE_RAPIDS_HOST}
      KAFKA_ADVERTISED_LISTENERS: LISTENER_INTERNAL://:${CORE_RAPIDS_LISTENER_INTERNAL_PORT},LISTENER_EXTERNAL://:${CORE_RAPIDS_LISTENER_EXTERNAL_PORT}
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_INTERNAL
      KAFKA_LISTENERS: LISTENER_INTERNAL://:${CORE_RAPIDS_LISTENER_INTERNAL_PORT},LISTENER_EXTERNAL://:${CORE_RAPIDS_LISTENER_EXTERNAL_PORT}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_INTERNAL:PLAINTEXT,LISTENER_EXTERNAL:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: ${CORE_RAPIDS_ZOOKEEPER_URL}
    ports:
      - ${CORE_RAPIDS_LISTENER_EXTERNAL_PORT}:${CORE_RAPIDS_LISTENER_EXTERNAL_PORT}

  rapids-zookeeper:
    image: zookeeper:3.5

  results:
    image: confluentinc/cp-kafka:5.4.1
    depends_on:
      - results-zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${CORE_RESULTS_HOST}
      KAFKA_ADVERTISED_LISTENERS: LISTENER_INTERNAL://:${CORE_RESULTS_LISTENER_INTERNAL_PORT},LISTENER_EXTERNAL://:${CORE_RESULTS_LISTENER_EXTERNAL_PORT}
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_INTERNAL
      KAFKA_LISTENERS: LISTENER_INTERNAL://:${CORE_RESULTS_LISTENER_INTERNAL_PORT},LISTENER_EXTERNAL://:${CORE_RESULTS_LISTENER_EXTERNAL_PORT}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_INTERNAL:PLAINTEXT,LISTENER_EXTERNAL:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: ${CORE_RAPIDS_ZOOKEEPER_URL}
    ports:
      - ${CORE_RESULTS_LISTENER_EXTERNAL_PORT}:${CORE_RESULTS_LISTENER_EXTERNAL_PORT}

  results-zookeeper:
    image: zookeeper:3.5
