version: "3"

services:
  rapids:
    image: confluentinc/cp-kafka:5.4.1
    depends_on:
      - rapids-zookeeper
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_INTERNAL://${CORE_RAPIDS_HOST}:29092,LISTENER_EXTERNAL://${CORE_RAPIDS_HOST}:${CORE_RAPIDS_PORT}
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_INTERNAL
      KAFKA_LISTENERS: LISTENER_INTERNAL://${CORE_RAPIDS_HOST}:29092,LISTENER_EXTERNAL://${CORE_RAPIDS_HOST}:${CORE_RAPIDS_PORT}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_INTERNAL:PLAINTEXT,LISTENER_EXTERNAL:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: ${CORE_RAPIDS_ZOOKEEPER_URL}
    ports:
      - ${CORE_RAPIDS_PORT}:${CORE_RAPIDS_PORT}

  rapids-zookeeper:
    image: zookeeper:3.5

  results:
    image: confluentinc/cp-kafka:5.4.1
    depends_on:
      - results-zookeeper
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_INTERNAL://${CORE_RESULTS_HOST}:29092,LISTENER_EXTERNAL://${CORE_RESULTS_HOST}:${CORE_RESULTS_PORT}
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_INTERNAL
      KAFKA_LISTENERS: LISTENER_INTERNAL://${CORE_RESULTS_HOST}:29092,LISTENER_EXTERNAL://${CORE_RESULTS_HOST}:${CORE_RESULTS_PORT}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_INTERNAL:PLAINTEXT,LISTENER_EXTERNAL:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: ${CORE_RESULTS_ZOOKEEPER_URL}
    ports:
      - ${CORE_RESULTS_PORT}:${CORE_RESULTS_PORT}

  results-zookeeper:
    image: zookeeper:3.5
