version: '3.5'

services:
  rapids:
    image: confluentinc/cp-kafka:5.4.1
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://:${CORE_RAPIDS_INTERNAL_PORT},EXTERNAL://:${CORE_RAPIDS_PORT}
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: INTERNAL://:${CORE_RAPIDS_INTERNAL_PORT},EXTERNAL://:${CORE_RAPIDS_PORT}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: ${CORE_RAPIDS_ZOOKEEPER_HOST}:${CORE_RAPIDS_ZOOKEEPER_PORT}
    networks:
      - core-rapids-internal-network
      - core-rapids-network
    ports:
      - ${CORE_RAPIDS_PORT}:${CORE_RAPIDS_PORT}

  zookeeper:
    image: zookeeper:3.5
    networks:
      - core-rapids-internal-network

networks:
  core-rapids-internal-network: {}
  core-rapids-network:
    name: core-rapids-network
