version: "3"

services:
  ask:
    build: ./ask
    environment:
      PRODUCT_REDIS_HOST: ${PRODUCT_REDIS_HOST}
      PRODUCT_REDIS_PORT: ${PRODUCT_REDIS_PORT}
      CORE_RAPIDS_URL: ${CORE_RAPIDS_URL}
    depends_on:
      - redis
    ports:
      - 8081:8080
    volumes:
        - ./ask/node_modules:/app/node_modules
        - ./ask:/app

  client:
    build: ./client
    depends_on:
      - ask
    environment:
      PRODUCT_ASK_URL: ${PRODUCT_ASK_URL}
    ports:
      - 8080:8080
    volumes:
      - ./client/node_modules:/app/node_modules
      - ./client:/app

  redis:
    image: redis:5-alpine
