version: '3.5'

services:
  ask:
    build: ./ask
    environment:
      CORE_RAPIDS_URL: ${CORE_RAPIDS_HOST}:${CORE_RAPIDS_PORT}
      PORT: ${PRODUCT_ASK_PORT}
      PRODUCT_REDIS_HOST: ${PRODUCT_REDIS_HOST}
      PRODUCT_REDIS_PORT: ${PRODUCT_REDIS_PORT}
    depends_on:
      - redis
    networks:
      - core-rapids-network
      - product-client-network
      - product-redis-network
    ports:
      - ${PRODUCT_ASK_PORT}:${PRODUCT_ASK_PORT}
    volumes:
        - ./ask/node_modules:/app/node_modules
        - ./ask:/app

  client:
    build: ./client
    depends_on:
      - ask
    environment:
      PORT: ${PRODUCT_CLIENT_PORT}
      PRODUCT_ASK_URL: ${PRODUCT_ASK_HOST}:${PRODUCT_ASK_PORT}
    networks:
      - product-client-network
    ports:
      - ${PRODUCT_CLIENT_PORT}:${PRODUCT_CLIENT_PORT}
    volumes:
      - ./client/node_modules:/app/node_modules
      - ./client:/app

  redis:
    image: redis:5-alpine
    networks:
      - product-redis-network

networks:
  core-rapids-network:
    name: core-rapids-network
  # core-results-network:
  #   name: core-results-network
  product-client-network: {}
  product-redis-network: {}
